### ISSUE TITLE
Nothing happens 

### ISSUE THREAD

**Issue by gusmuncher** [Sammy1Am/Moppy2#200] opened 2023-09-21 18:15 UTC
I cannot for the life of me figure out what i am doing wrong.
When i press the reset button all the floppy drive head does is move a little bit or make a loud beep and nothing else.
Opening the Moppy GUI and playing something does nothing.
Re uploading the sketch to the arduino results in the same thing happening.
I have tried this on three different floppy drives and they all do the exact same thing.

the IDE shows no errors.
the light on the drive is on 
the pins are properly connected 
tapping the pins shows that the drives work perfectly fine.

I am sorry for making another issue report but i am genuinely lost.

https://github.com/Sammy1Am/Moppy2/assets/144593320/798a512d-c053-45b3-830b-ece73677f4dd

**Comment by Sammy1Am** [comment] 2023-09-21 22:09
Duplicate of #198

**Closed by Sammy1Am** 2023-09-21 22:09 UTC
