### ISSUE TITLE
Problem with java/netbeans

### ISSUE THREAD

**Issue by Adelin990** [Sammy1Am/Moppy2#114] opened 2020-12-02 14:45 UTC
Hello 
I'm having a hard time making it work with netbeans 
when i run the project a new window appears where i can load a midi file , connect the arduino and so on 
The problem is that when i press the "connect" button the window just disappears and i get an error in netbeans : 

A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006af4862e, pid=14284, tid=0x00000000000010d8
#
# JRE version: Java(TM) SE Runtime Environment (8.0_271-b09) (build 1.8.0_271-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.271-b09 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [libNRJavaSerial.dll+0x862e]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows 

i can attach the whole log if needed.

**Comment by Sammy1Am** [comment] 2020-12-02 19:32
Looks like a duplicate of #86 .  Please make sure you're using the latest Moppy 2.0 code, MoppyClassic is old and unsupported now.

Also, it looks like you're using Java 8; you should use *at least* Java 12 with Moppy (but even 12 is a bit out of date these days, 15 is probably best).

**Closed by Sammy1Am** 2020-12-02 19:32 UTC
